---
- name: "Install default Apache Web Server"
  hosts: host_servers
  become: true

  tasks:
  - name: "Install Apache WebServer"
    ansible.builtin.apt: name=apache2 state=latest

  - name: "Start Apache and Enable it on the every boot"
    ansible.builtin.service: name=apache2 state=started enabled=true
