---
- name: "Install Apache and Upload my Home Page"
  hosts: all
  become: true

  vars:
    source_file: "./MyWebSite/index.html"
    destin_file: "/var/www/html"

  tasks:
  - name: "Check and Print LINUX Version"
    debug:
      var: ansible_os_family

  - name: "Install Apache Web Server for RedHat"
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: "Install Apache Web Server for Debian"
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: "Copy HomePage file to Web Server"
    copy:
      src: "{{ source_file }}"
      dest: "{{ destin_file }}"
      mode: 0555
#    notify: Restart Apache

  - name: "Start Web Server service for RedHat"
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

  - name: "Start Web Server service for Debian"
    service:
      name: apache2
      state: started
      enabled: true
    when: ansible_os_family == "Debian"

  handlers:
  - name: "Restart Apache RedHat"
    service:
      name: httpd
      state: restarted

  - name: "Restart Apache Debian"
    service:
      name: apache2
      state: restarted
...

