---
- name: "Install default Apache Web Server"
  hosts: host_servers
  become: true

  tasks:

  - block:

    - name: "Install Apache WebServer for Debian"
      ansible.builtin.apt: name=apache2 state=latest

    - name: "Start Apache and Enable it on the every boot"
      ansible.builtin.service: name=apache2 state=started enabled=true

    when: ansible_os_family == "Debian"

  - block:

    - name: "Install Apache WebServer for RedHat"
      yum: name=httpd state=latest

    - name: "Start WebServer service for RedHat"
      service: name=httpd state=started enabled=true

    when: ansible_os_family == "RedHat"

