---
- name: "Test playbook"
  hosts: all
  become: true


  vars:
    message1: Privet
    message2: World
    secret: FDJSJFLSJFLKSDJFSJFJSL

  tasks:

  - name: "Print Secret variable"
    debug:
      var: secret

  - debug:
      msg: "Secret word {{ secret }}"

  - debug:
      msg: "Owner this server -->{{ owner | default('Not specified') }}"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }} "

  - debug:
      msg: "Full message --> {{ full_message }}"

  - shell: uptime
    register: results

  - debug:
      var: results.stdout
...
